### ISSUE TITLE
Metadata doesn't show maintainer

### ISSUE THREAD

**Issue by jcsackett** [juju/charmstore#140]
id/meta/charm-metadata doesn't include the maintainer parameter; likewise it cannot be found via the /meta endpoint.

It looks like this information isn't pulled in during ingest.

**Comment by mitechie** [comment]
We're not using the maintainer field in the charm because it lies during forks. We are, however, showing the charm branch owner as the maintainer until we have login info to show a proper user account. Can you get the branch owner information?

**Comment by jcsackett** [comment]
As commented in issue #141, there's no bzr information, including the branch owner; it does look like extra-info sometimes contains bzr-digest, but that doesn't necessarily correspond to the necessary info.

**Comment by urosj** [comment]
Resolved.
