### ISSUE TITLE
No way to get bzr revisions via charmstore

### ISSUE THREAD

**Issue by jcsackett** [juju/charmstore#141]
We have no means of getting the bzr information (formerly in code_source in charmworld). The spec specifically indicates this isn't going to be implemented, but there are clients of the charmstore that need this information.

**Comment by mitechie** [comment]
Guess we're not getting the branch owner currently either. Thanks for this bug, I've added it to the top of the charmstore work.

**Comment by jcsackett** [comment]
Correct, there's none of the bzr data.
