### ISSUE TITLE
Cannot use svg link in img tags from charmstore

### ISSUE THREAD

**Issue by jcsackett** [juju/charmstore#146]
We can't use the /charm/archive/icon.svg path inside img tags as we can from the charmworld API; the svg does not load, and is identified as being in the broken state.

The mime-type is being correctly set (svg+xml); given inspection of the headers from the charmstore and charmworld, it's _likely_ something to do with access controls, but I'm not certain.

charmworld:

```
{'content-length': '2718', 'via': '1.0 localhost (squid/3.1.19)', 'x-cache': 'MISS from localhost', 'content-encoding': 'gzip', 'x-cache-lookup': 'HIT from localhost:3128', 'vary': 'Accept-Encoding', 'server': 'gunicorn/0.17.2', 'etag': '"339d47da84323f27be49415223f17b1b"', 'cache-control': 'max-age=86400, public', 'date': 'Wed, 15 Oct 2014 01:04:04 GMT', 'access-control-allow-origin': '*', 'access-control-allow-headers': 'X-Requested-With', 'content-type': 'image/svg+xml'}
```

charmstore:

```
{'date': 'Wed, 15 Oct 2014 01:11:39 GMT', 'content-length': '10701', 'content-type': 'image/svg+xml'}
```

**Comment by mitechie** [comment]
This is a CORS issue, chrome shows the error:

```
Image from origin 'http://juju.mycomiclife.net' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:6543' is therefore not allowed access.
```

combo?app/utils.js&app/views/detail-view.js&app/views/charm-view.js&app/views/bundle-view.js&app/co…:137 Uncaught InvalidStateError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state.

The charmstore should support full CORS and send the correct headers. 

```
http://bazaar.launchpad.net/~juju-gui-bot/charmworld/trunk/view/head:/charmworld/views/api/__init__.py#L586
```

**Comment by urosj** [comment]
CORS resolved. $ID/icon.svg & $ID/diagram.svg enpoints created.
