### ISSUE TITLE
expand-id doesn't provide what charm version will be deployed

### ISSUE THREAD

**Issue by jcsackett** [juju/charmstore#149]
We need a means of determining, provided e.g. 'mysql', what charm-id will actually be deployed e.g. 'cs:trusty/mysql-7'; also provided 'precise/mysql' which revno will be deployed e.g. 'cs:precise/mysql-48'

The current API provides expand-id, which gives us _all_ possible IDs lexicographically sorted -- the same list for both cases. We can work with that for now, but it requires a lot of processing on the client end. There should be a means of determining what the actual deployed version will be based on either of those partial id patterns.

This may not be part of expand-id, but it should exist somewhere in reasonably accessible form.

**Comment by mitechie** [comment]
This is the start of making sure the client can accept from the user a limited name 'mysql' or '~rharding/mysql' and having the charmstore resolve that out to the full ids that would be used in a 'juju deploy mysql' scenario. Repeating this logic in the client and having different client resolve it differently would be less than ideal.

**Comment by jcsackett** [comment]
Note also the need for "precise/mysql" to resolve put along with the examples @mitechie pointed out.

**Comment by jcsackett** [comment]
This data can be found through the /$id/meta/any endpoint.
