### ISSUE TITLE
Not all charms are getting bzr info

### ISSUE THREAD

**Issue by jcsackett** [juju/charmstore#172]
On http://juju.mycomiclife.net/cs/v4/~lazypower/precise/errbit-0/meta/extra-info

The extra-info parameter is returning only `{"bzr-digest":"chuck@dasroot.net-20131226021137-xvizyag5zgp4015u"}`

**Comment by jcsackett** [comment]
I see that it's possible this isn't fully implemented; but http://juju.mycomiclife.net/cs/v4/bundle/mongodb-cluster/meta/extra-info for example _does_ have the info.

**Comment by urosj** [comment]
We _should_ get all the info that is available in charmworld. Is that one available from charmworld?

**Comment by mitechie** [comment]
thanks @urosj, this is not in charmworld. Closing as an invalid bug for now unless we find this as a huge problem.
