### ISSUE TITLE
id/expand-id might return too much, mixing bundles and charms

### ISSUE THREAD

**Issue by urosj** [juju/charmstore#193]
When expand-id is called on a bundle, we return charms with the same name as well. This will not be a problem with a flat namespace, as such collisions will not be allowed.

**Comment by mitechie** [comment]
While the api is not a flat namespace the storefront is as a client. I think it'd be great to start enforcing the 'one name per namespace' rather than trying to filter out results in the return value. The api doesn't have to be flat yet, but it can make sure the data fits that model.

**Comment by rogpeppe** [comment]
Fixed by PR #198
