### ISSUE TITLE
search api does not allow sorting parameters

### ISSUE THREAD

**Issue by mitechie** [juju/charmstore#212]
We need to be able to perform a search and sort by for the UI. This will be especially important when we start working out a pagination strategy.

Name (alphabetise A-Z)
Owner (alphabetise A-Z)
Deploys (descending order 100-1)
Units (descending order 100-1)
Series (Latest to oldest)

**Comment by urosj** [comment]
We'll add sorting by name for now, but I think that sorting should be done
on the client side, otherwise SF is making a search query for every user
action on sort (on same results).

**Comment by mitechie** [comment]
My concern with doing it client side is that we know we want to get to a pagination story and with a limit/offset in the api sorting client side isn't feasible for large data sets.

**Comment by urosj** [comment]
Yes, pagination includes all other sorts of concerns here. You see one set
of results, then press "sort on series" and get completely different one.
We should make sure that UX is ok with this. Esp. as search is not the same
as listing of content. I'm playing with the idea of introducing /enlist API
endpoint that would not deal with boosting as ES does but just provide
mongo collection view. However, it's just an idea so far.

**Comment by urosj** [comment]
This is implemented now.
