### ISSUE TITLE
Include legacy download counts

### ISSUE THREAD

**Issue by jcsackett** [juju/charmstore#217]
Legacy data for download counts show a lot of activity that we did not include in the new charmstore.

See counts on http://manage.jujucharms.com/charms/trusty/wordpress vs https://api.jujucharms.com/v4/trusty/wordpress/meta/any?include=stats

While there are good reasons to reset the count, this has led to a lot of negative feedback about the zero counts.

**Comment by urosj** [comment]
/meta/stats now returns dl stats from charm world. I'll keep this bug open.
