### ISSUE TITLE
Need endpoint to fetch all available revision numbers

### ISSUE THREAD

**Issue by hatched** [juju/charmstore#223]
The GUI currently allows the user to upgrade from revno 0 to latest for all charms when the user clicks to 'Change version' Because not all revno's exist it would be nice if we could query a charmstore endpoint to get all available revision numbers that the user could up/downgrade to.

**Comment by mitechie** [comment]
so I think the thing is that we want to know where a given revision is in the history list. So maybe we only need a set behind/in front of a specified revision, maybe all if we think that'll do. There's some room there.

**Comment by mitechie** [comment]
https://api.staging.jujucharms.com/v4/mongodb-5/meta/revision-info works closing
