### ISSUE TITLE
Promulgation of new charm get a wrong revision

### ISSUE THREAD

**Issue by urosj** [juju/charmstore#268]
http get https://api.jujucharms.com/v4/~charmers/trusty/mellanox-0/meta/extra-info

vs

http get https://api.jujucharms.com/v4/trusty/mellanox-0/meta/extra-info
http get https://api.jujucharms.com/v4/trusty/mellanox-1/meta/extra-info

The wrong revision of promulgated charm happened on all testing machines as well.

**Comment by rogpeppe** [comment]
I can't reproduce this locally (assuming that you're referring to the fact that
http get https://api.jujucharms.com/v4/trusty/mellanox-0/meta/extra-info returns
a not-found error)

Have you got a copy of the log where you reproduced the issue?

**Comment by urosj** [comment]
Sorry, the /v4/mellanox-0/meta/extra-info does not exist, while it does in ~charmers namespace. All looks fine for revision 1 of both promulgated and ~charmers.
