### ISSUE TITLE
Icon request returns with a 500 when svg is invalid

### ISSUE THREAD

**Issue by hatched** [juju/charmstore#301]
https://api.jujucharms.com/charmstore/v4/~hloeung/precise/apache2-2/icon.svg returns with a 500 and the body content of 
`{"Message":"failed to read token: XML syntax error on line 3: invalid UTF-8","Code":""}` which causes a broken image when viewed in the GUI. Charmstore should probably return the default image if there are any issues with the svg's

**Comment by mitechie** [comment]
This is actually deeper I think. Notice that there was an issue with the cloudfoundry icon reported in another bug. The team then upadted the icon and now 

https://api.jujucharms.com/v4/~cf-charmers/trusty/cloudfoundry-205/archive/icon.svg

works correctly and returns a nice icon while the short cut

https://api.jujucharms.com/v4/~cf-charmers/trusty/cloudfoundry-205/icon.svg

does not. I think there's a bug in the shortcut not updating with the archive perhaps?
