### ISSUE TITLE
https://api.jujucharms.com/v4/trusty/juju-gui/expand-id still shows precise ids

### ISSUE THREAD

**Issue by mitechie** [juju/charmstore#307]
Since I've narrowed it down to /trusty/juju-gui I had expected it to only show me ids for the trusty version of the charm. 

I'd expect the current list for https://api.jujucharms.com/v4/juju-gui/expand-id

**Comment by urosj** [comment]
This is by design. Expand id shows all versions & revisions of a charm as
described here: API.md
https://github.com/juju/charmstore/blob/v4/docs/API.md#expand-id

**Comment by mitechie** [comment]
Hmm, is the design open for debate?

**Comment by urosj** [comment]
Of course. I was thinking of adding a "&series=" kind of endpoint. Would
that be ok for UI needs?

**Comment by mitechie** [comment]
The store has this model of "give me enough info and I'll find the rest for you" so I had expected that if I limited things with a series in the url that it would naturally realize that and show me ids for things that match that. 

Adding &series as a parameter means the url just really feels odd. 

```
/trusty/juju-gui?series=trusty 
```

I really prefer the idea that we just respect the optional series in the url and if you have none you get all series. What do you think? Is there something to this that doesn't work out well I'm not thinking of at the moment?
