### ISSUE TITLE
bundle metadata missing Tags field 

### ISSUE THREAD

**Issue by mitechie** [juju/charmstore#315]
The charm has it in charm-metadata: 
https://api.jujucharms.com/v4/mongodb/meta/charm-metadata

However bundles don't have it though it's in the charmworld data:
https://api.jujucharms.com/v4/~jcsackett/bundle/mongodb-cluster-0/meta/bundle-metadata
http://manage.jujucharms.com/api/3/search?text=jcsackett

**Comment by mitechie** [comment]
As uros points out, the tags field doesn't make it across the bundles.yaml -> bundle.yaml transformation:

https://api.jujucharms.com/v4/%7Ejcsackett/bundle/mongodb-cluster-0/archive/bundle.yaml
https://api.jujucharms.com/v4/~jcsackett/bundle/mongodb-cluster-0/archive/bundles.yaml.orig

**Comment by mitechie** [comment]
Hmm, this should be fixed but the example here still fails because we didn't migrate the old data at all. 

Will leave open until a bundle with a tag lands so we can verify the fix is available. 

What is the thought on updating existing data for situations like this?

**Comment by frankban** [comment]
@rogpeppe could you please check this?

**Comment by urosj** [comment]
Invalidated with new charm push command.
