### ISSUE TITLE
Related charms provides and requires are reversed

### ISSUE THREAD

**Issue by hatched** [juju/charmstore#318]
Compare the YAML file https://api.jujucharms.com/v4/trusty/glance-12/archive/metadata.yaml with the response from the api: https://api.jujucharms.com/charmstore/v4/precise/glance-39/meta/any?include=charm-related .

When this fix goes out the GUI will need to be updated along with any other consumers of this endpoint.

**Comment by frankban** [comment]
Not sure about the charm store semantic in this one, but better to behave in the way users expect.

**Comment by urosj** [comment]
@hatched is GUI still using this anywhere? The /meta/any?... is linking to any related charm.

**Comment by hatched** [comment]
@urosj The GUI uses the /meta/any endpoint when requesting entity (charm/bundle) details along with a list of includes.

**Comment by urosj** [comment]
@hatched LOL, i know that. I was wondering about this specific charm-related call from the bug.

**Comment by frankban** [comment]
The GUI does not retrieve charm-related anymore.
