### ISSUE TITLE
charmstore returns 500 and a true error message when archive is not validated

### ISSUE THREAD

**Issue by jrwren** [juju/charmstore#372]
I used `juju charm create test` and changed nothing, then `cd test; zip -ur ../test.zip .` and tried to upload.

```
HTTP/1.1 500 Internal Server Error
Access-Control-Allow-Headers: X-Requested-With
Access-Control-Allow-Origin: *
Content-Length: 134
Content-Type: application/json
Date: Thu, 07 May 2015 13:25:25 GMT

{
    Message: "interface interface-name in relation provides-relation has almost certainly not been changed from the template"
    Code: ""
}
```

I'd expect a 400 level error instead of a 500 level error. Maybe a 422 or a 400.

**Comment by urosj** [comment]
@jrwren is this still relevant?

**Comment by jrwren** [comment]
I think this is no longer relevant because "upload" is now `charm push`, which hides the HTTP code.
