### ISSUE TITLE
changes api not just showing new stuff from that day

### ISSUE THREAD

**Issue by mitechie** [juju/charmstore#388]
https://api.jujucharms.com/charmstore/v4/changes/published?from=20-05-2015&to=21-05-15

It's got ~charmers/cassandra with all the revisions spread across it.

**Comment by urosj** [comment]
Implementation is not in-sync with the docs. Instead of from and to, we use start and stop. And the date format is YYYY-MM-DD. So the proper call would be:

https://api.jujucharms.com/charmstore/v4/changes/published?start=2015-05-20&stop=2015-05-21

Also, stop is not needed is stop is "now".
