### ISSUE TITLE
csclient/* states it is LGPLv3 and points to the AGPL LICENSE

### ISSUE THREAD

**Issue by sinzui** [juju/charmstore#409]
We need to resolve the license contention in this project to put juju 1.24.2 into Ubuntu.

Either csclient/\* are AGPL, or the LGPLv3 license needs to be added and the files point to it.

**Comment by urosj** [comment]
@sinzui let us know if there's anything else that needs to be done.

**Comment by frankban** [comment]
I think this is solved now. Please reopen if I am wrong.
