### ISSUE TITLE
base entity not removed when the last revision of an entity is deleted

### ISSUE THREAD

**Issue by frankban** [juju/charmstore#413]
Base entities are never deleted, even if the last (or only) revision of the corresponding entities is deleted via the DELETE api call to the archive endpoint.
This can be problematic as the base entity stores, among other things, ACLs for related charms and bundles. So when the same entity is uploaded again it will automatically inherit the preexisting ACLs, which can be unexpected and confusing.

**Comment by rogpeppe** [comment]
The obvious thing to do here is to refcount base entities, but that makes for an extremely fragile store and is something we probably don't want to do.

Another implementation possibility might be to check when adding an entity whether the revision id is 0, and if so, to clear out any existing base entity, although that is inevitably racy.

**Comment by frankban** [comment]
I'll close this as we need to have a different deletion strategy.
