### ISSUE TITLE
Incorrect unit/machine count

### ISSUE THREAD

**Issue by fabricematrat** [juju/charmstore#520]
Comparing 
https://api.jujucharms.com/charmstore/v4/realtime-syslog-analytics/meta/bundle-metadata
and 
https://api.jujucharms.com/charmstore/v4/realtime-syslog-analytics/meta/bundle-machine-count
or 
https://api.jujucharms.com/charmstore/v4/realtime-syslog-analytics/meta/bundle-unit-count

We get a score of 9 but 
compute-slave: {
NumUnits: 3,

So it should be 11.

This has been reported on jujucharms.com.

**Comment by mhilton** [comment]
I see us getting a unit and machine count of 8, but three of the charms are subordinates so I think that is correct for machine count. unit count is a little more complex, but I would argue that 8 is correct there too.
