### ISSUE TITLE
Revision mismatch between user namespace and promulgated URL

### ISSUE THREAD

**Issue by urosj** [juju/charmstore#627]
Realtime analytics bundle Rev15.

https://api.jujucharms.com/charmstore/v5/bundle/realtime-syslog-analytics/meta/owner and https://api.jujucharms.com/charmstore/v5/bundle/realtime-syslog-analytics/meta/any state revision 15.

https://api.jujucharms.com/charmstore/v5/bundle/realtime-syslog-analytics-15/meta/published shows it's the default stable revision.

However:
https://api.jujucharms.com/charmstore/v4/~bigdata-charmers/bundle/realtime-syslog-analytics/meta/any
Points to revision 1.
https://api.jujucharms.com/charmstore/v5/~bigdata-charmers/bundle/realtime-syslog-analytics/meta/published
Also shows it's the default.

Once charm store is fixed, this will be resolved.

@mhilton @rogpeppe @fabricematrat PTAL.

**Comment by mhilton** [comment]
I believe this is correct the behavior. The realtime-syslog-analytics bundle has the following lineage:

```
bundle/realtime-syslog-analytics-6  -> ~charmers/bundle/realtime-syslog-analytics-6
bundle/realtime-syslog-analytics-7  -> ~charmers/bundle/realtime-syslog-analytics-7
bundle/realtime-syslog-analytics-8  -> ~charmers/bundle/realtime-syslog-analytics-8
bundle/realtime-syslog-analytics-9  -> ~charmers/bundle/realtime-syslog-analytics-9
bundle/realtime-syslog-analytics-10 -> ~charmers/bundle/realtime-syslog-analytics-10
bundle/realtime-syslog-analytics-11 -> ~charmers/bundle/realtime-syslog-analytics-11
bundle/realtime-syslog-analytics-12 -> ~charmers/bundle/realtime-syslog-analytics-12
bundle/realtime-syslog-analytics-13 -> ~charmers/bundle/realtime-syslog-analytics-13
bundle/realtime-syslog-analytics-14 -> ~bigdata-charmers/bundle/realtime-syslog-analytics-0
bundle/realtime-syslog-analytics-15 -> ~bigdata-charmers/bundle/realtime-syslog-analytics-1
```

**Comment by urosj** [comment]
@mhilton you're right. It was misbehaviour of GUI that caused the confusion. Closing this issue.
