### ISSUE TITLE
Require a LICENSE not a copyright

### ISSUE THREAD

**Issue by ghost** [juju/charmstore#632]
The current charm proof command requires a "copyright" file. Well my charms are going to have a LICENSE that hold a copyleft. The naming of things is important, so please update this to be less biased.

[https://jujucharms.com/docs/devel/authors-charm-policy](https://jujucharms.com/docs/devel/authors-charm-policy)

**Comment by frankban** [comment]
Moved to https://bugs.launchpad.net/charm-helpers/+bug/1591176
