### ISSUE TITLE
Bundle search is broken

### ISSUE THREAD

**Issue by AdamIsrael** [juju/charmstore#639]
If I [browse](https://jujucharms.com/store?type=bundle) the charm store for bundles, I get plenty of results. I see openstack and lots of apache bundles.

But if I do a search for [openstack](https://jujucharms.com/q/openstack) and then change the search type from All to [Bundles](https://jujucharms.com/q/openstack?type=bundle), I get zero results. Same behavior if I search for apache.

**Comment by mitechie** [comment]
Guys, this is a big one. We need to try to get this through to production with this fix asap please. We've got many folks attempting to use the store that are effected by this.

**Comment by mitechie** [comment]
To be clear, this is worth a Friday deployment exception.

**Comment by makyo** [comment]
Fix landed by @mhilton, will be deployed ASAP, I believe

**Comment by urosj** [comment]
This is on staging ATM and will be in production on Monday. You can see the results here now: 
https://staging.jujucharms.com/q/openstack

**Comment by mitechie** [comment]
Deploy is up and https://jujucharms.com/q/openstack?type=bundle filters on bundles with openstack in the search. 

There's some more work to be done, but I'm closing this one atm. Please verify it's better for you and reopen with notes if you have more issues.
