### ISSUE TITLE
metrics into entities migration fails.

### ISSUE THREAD

**Issue by jrwren** [juju/charmstore#644]
2016-06-21 12:33:29 INFO charmstore.internal.charmstore migrations.go:107 starting migration: store metrics into entities
cannot create new server at "0.0.0.0:8080": database migration failed: error executing migration: store metrics into entities: cannot read charm archive bytes: yaml: unmarshal errors:
  line 1: cannot unmarshal !!seq into map[string]charm.Option

**Comment by frankban** [comment]
Fixed, some charms have been ingested in the past using yaml.v1 which allows empty lists to be unmarshaled as maps. These charms are no longer deployable, but still in the db. To work around this issue, the migration now ignores such errors: this is safe to do especially considering that these entities surely don't have metrics.
