### ISSUE TITLE
V3 API Broken

### ISSUE THREAD

**Issue by adam-stokes** [juju/charmstore#657]
We are hitting a bug in our openstack installer software on trusty where we've been using the older (but assumed stable) api:

https://manage.jujucharms.com/api/3/charm/trusty/keystone

This brings up keystone-198 as the latest charm revision where it should be pulling keystone-255. Something has changed on the backend I imagine to make this call return incorrect information.

**Comment by adam-stokes** [comment]
@mitechie

**Comment by mikemccracken** [comment]
More detail:

for https://manage.jujucharms.com/api/3/charm/trusty/keystone 
line 169 says "id": "trusty/keystone-198"

for https://api.jujucharms.com/charmstore/v4/meta/any?include=charm-metadata&id=cs:trusty/keystone 
line 6 says "Id": "cs:trusty/keystone-255",

**Comment by btro** [comment]
so, will this bug be fixed any time soon? I still have exactly this error message for the multi install and I have no idea how to fix it. I'd be so thankful if you could give me a hint how I can fix this myself.

**Comment by adam-stokes** [comment]
Multi install is deprecated in favor of http://conjure-up.io
