### ISSUE TITLE
bundles docs are unclear about required vs. optional top level keys

### ISSUE THREAD

**Issue by mikemccracken** [juju/charmstore#683]
the file `docs/bundles.md` does not state which top level keys are required. I had to ask on #juju to hear that `series` is not required. I know that `machines` is not required from experience, but that's also not explicitly stated.

Another related issue, this appears to be the most complete documentation of the bundle file formats, but it doesn't seem to have been meant to be that - in the first sentence, it points to github.com/juju/charm , but there are no docs there, only code.

**Comment by rogpeppe** [comment]
The bundle docs don't really in the charmstore. The definitive documentation appears to be [here](https://docs.jujucharms.com/2.3/en/charms-bundles).

I'll add an issue to remove `docs/bundles.md`.
