### ISSUE TITLE
ERROR cannot post archive: unrecognized series "zesty" in metadata

### ISSUE THREAD

**Issue by ryan-beisner** [juju/charmstore#695]
We've started to enable the Zesty series metadata in OpenStack Charm CI, but it looks like the charm store needs to be made aware that it is a thing:

ERROR cannot post archive: unrecognized series "zesty" in metadata

We've already committed zesty series metadata to several charm repos, and this is preventing push/release to the charm store.

**Comment by ryan-beisner** [comment]
As a general ongoing process, the charm store should be made aware of the new development series as soon as it opens.

**Comment by ryan-beisner** [comment]
To unblock devs in the mean time, we've removed zesty series metadata from the affected charm repos.  This means OpenStack CI and charm devs cannot test zesty charms in a charm store workflow at the moment.

**Comment by urosj** [comment]
This should be enabled now.
