### ISSUE TITLE
charm permission overwrite on release

### ISSUE THREAD

**Issue by mattyw** [juju/charmstore#698]
Steps to reproduce
```bash
charm grant \~mattyw/trusty/mycharm-0 --acl read --set mygroup
charm show cs:~mattyw/trusty/mycharm-0 # Confirm read permission shows mygroup
# Realise I forgot to release it
charm release cs:~mattyw/trusty/mycharm-0 --channel edge
charm show cs:~mattyw/trusty/mycharm-0 # Read permission no only shows mattyw - mygroup has been removed
```

**Comment by rogpeppe** [comment]
This is a feature and not a bug. There's a different set of ACLs for
each channel, so setting the ACL for the unpublished charm set the
ACL for all unpublished charms, then releasing it caused the
charm to use the (as yet unchanged) ACLs on the released channel.
