### ISSUE TITLE
Login page is an ugly experience

### ISSUE THREAD

**Issue by jameinel** [juju/charmstore#703]
See also https://bugs.launchpad.net/juju/+bug/1656246

Essentially, if you try to do:
 juju deploy cs:~user/mycharm

You end up getting launched into a browser, but all of the pages that you go through feel *very* unpolished, and you end up at a page that just says:
 login successful as user jameinel

And it doesn't even give you any information that you can close the page, or go back to the terminal, or anything actually useful. It just feels like a 'hacked together' experience instead of a nice step-by-step helping you through what you want.

**Comment by cmars** [comment]
@jameinel I understand what you mean about the final "login successful" page, but could you be more specific about the prior pages being "unpolished"?

**Comment by cmars** [comment]
@jameinel What would a useful step-by-step experience look like?

**Comment by jameinel** [comment]
Rick mentioned that "charm login" is able to do a fully text-ui based login, even doing 2-factor-auth. Probably Juju should just be using that.

Its hard to say as now that I'm logged in, I don't see the pages. The big thing is just that the overall user experience for "juju deploy cs:~foo/foo" does not feel like a pleasant experience. I'm hesitant to log out of everything cause then I'm not sure what else I'm logged out of (like google docs, etc.)

**Comment by mhilton** [comment]
charm login can only do a fully text based login if the user has previously logged in to jujucharms.com through Ubuntu SSO. This has caused confusion a number of times, where it looks like the user has logged in, but they still can't do the thing they were trying to do.

**Comment by mhilton** [comment]
Oh I will also add that we've had plenty of feedback from people who are uncomfortable typing their Ubuntu SSO password into a random text prompt as well.

**Comment by rogpeppe** [comment]
> all of the pages that you go through feel very unpolished

These are the standard USSO login pages, right? (excepting that final "login successful"
page). Perhaps we should raise an issue with the people responsible for maintaining
those.

**Comment by rogpeppe** [comment]
This has been significantly improved since this issue was raised.
