### ISSUE TITLE
charmstore redirecting to user namespace

### ISSUE THREAD

**Issue by jamesbeedy** [juju/charmstore#714]
When I try to access my team namespace https://jujucharms.com/u/creativedrive/, I am redirected to my usernamespace https://jujucharms.com/u/jamesbeedy/.

Also, only my models show ... no charms.

**Comment by simonklb** [comment]
I think juju-gui is where the actual issue is, check this: https://github.com/juju/juju-gui/issues/2476

**Comment by frankban** [comment]
@simonklb yes thanks, it can be closed here.
