### ISSUE TITLE
redirecting to non-existent routes

### ISSUE THREAD

**Issue by jamesbeedy** [juju/charmstore#715]
Not sure if this is an isolated instance or if it could be happening on a global level.

Take the barbican charm for example, from ~openstack-charmers-next.

![screen shot 2017-02-19 at 1 33 52 pm](https://cloud.githubusercontent.com/assets/5590546/23106826/384563e2-f6a8-11e6-8e46-d654f6d70404.png)

When I select the 'config.yaml' file, I get sent to "https://api.jujucharms.com/charmstore/v5/~openstack-charmers-next/xenial,yakkety/barbican/archive/config.yaml", and my page rendered displays:

![screen shot 2017-02-19 at 1 36 12 pm](https://cloud.githubusercontent.com/assets/5590546/23106837/69bdf92a-f6a8-11e6-84c7-ab631ad02d04.png)

**Comment by fabricematrat** [comment]
@jamesbeedy probably should be closed now. I think it is working correctly now.
