### ISSUE TITLE
Can't release

### ISSUE THREAD

**Issue by hloeung** [juju/charmstore#768]
Hi,

I'm a member of the team that owns the nrpe charm. I can't seem to release, keeps giving me access denied:

> [hloeung@dharkan tmp]$ charm release cs:~nrpe-charmers/nrpe-21
> ERROR cannot release charm or bundle: access denied for user "hloeung"

**Comment by xavpaice** [comment]
I get the same, plus the same for nagios-charmers for the nagios charm.

**Comment by urosj** [comment]
Nrpe is promulgated which means that release to stable can only be done by charmers, not nrpe-charmers.

**Comment by hloeung** [comment]
Oh? For livepatch, I was able to release a new one earlier today and that's promulgated to cs:canonical-livepatch.

**Comment by hloeung** [comment]
https://jujucharms.com/canonical-livepatch/12

**Comment by urosj** [comment]
Different permissions. See https://api.jujucharms.com/charmstore/v5/canonical-livepatch-12/meta/perm

**Comment by hloeung** [comment]
Uros, thank you so much for tracking this down. This seems to have fixed it:

> charm grant ~nrpe-charmers/nrpe --acl write --set charmers,nrpe-charmers
