### ISSUE TITLE
Non-stable charms link to incorrect URL

### ISSUE THREAD

**Issue by paulgear** [juju/charmstore#770]
I've just released cs:~prometheus-charmers/grafana-5 to candidate.  If I go to https://jujucharms.com/u/prometheus-charmers/grafana/, it says stable is cs:~prometheus-charmers/grafana-3, and the latest version is 5, but the link to version 5 is to https://jujucharms.com/grafana/5, which doesn't exist.  The link should be to https://jujucharms.com/u/prometheus-charmers/grafana/5, which exists, and works as expected.

**Comment by fabricematrat** [comment]
@paulgear Hi, I think this is solved now, could you have a look ?

**Comment by paulgear** [comment]
@fabricematrat Doesn't appear to be. If you use https://jujucharms.com/u/ntp-team/ntp/ as the example, stable is rev 13, candidate is 14, and the link in the header is to https://jujucharms.com/ntp/14, which doesn't exist, but https://jujucharms.com/u/ntp-team/ntp/14 does.

**Comment by rogpeppe** [comment]
@paulgear We think this is fixed now. Could you check again please?

**Comment by paulgear** [comment]
https://jujucharms.com/u/ntp-team/ntp/ looks good now - thanks!
