### ISSUE TITLE
identity manager login failing

### ISSUE THREAD

**Issue by mhilton** [juju/charmstore#783]
We are seeing a problem with one of the production charmstore servers not being able to log in to identity manager to check user information.

```
ERROR cannot retrieve current username: cannot fetch groups: cannot get discharge from "https://api.jujucharms.com/identity": cannot start interactive session: macaroon discharge required
```

Interestingly this is only affecting one of the two units.

**Comment by rogpeppe** [comment]
This was due to out of sync clocks on two servers.
