### ISSUE TITLE
Empty resource responses.. bug?

### ISSUE THREAD

**Issue by shousper** [juju/charmstore#816]
Are [resource links](https://api.jujucharms.com/charmstore/v5/~containers/kubernetes-master-122/resource/kube-apiserver/0) supposed to give a successful empty response?

All the resources [here](https://jujucharms.com/u/containers/kubernetes-master/) don't seem to be loading anything. I was reading though [this document](https://jujucharms.com/canonical-kubernetes/) under "Known Limitations and Issues" after having issues with a localhost deployment.. and saw this:

> If resources fail to download during initial deployment for any reason, you will need to download and install them manually.

So I was wondering.. how do I manually download resources? haha

**Comment by fabricematrat** [comment]
Those resources have been uploaded as empty deliberatly
During deployment they need to be specified.
The charm documentation should specify where to find those resources.
Please submit a bug to the charm author.
