### ISSUE TITLE
Bundle paths and visibility issues

### ISSUE THREAD

**Issue by hatched** [juju/charmstore#828]
There is some confusion around why https://jujucharms.com/u/rharding/gypsy-danger-testing/ returns a 404 but https://jujucharms.com/u/james-page/openstack-in-containers/ does not.

The first path does not have a published bundle with a revno 1 but the second one does. Shouldn't a link with no revno return the latest?

Also the `gypsy-danger-testing/2` shows that it is unpublished in the UI. Should the charmstore be returning unpublished charms?

**Comment by frankban** [comment]
I'd be -1 on changing any charm store resloving logic right now, as we are investigating how to make channels work similar to snap store. That said, channels are exactly the way we use to resolve entities when a revision is not specified, so it would feel a bit weird to return unpublished stuff when no revision is provided. Surely, we could handle confusion on the storefront side, for example by suggesting the unpublished full URL in case of 404.

**Comment by rogpeppe** [comment]
This is working as designed AFAICS. Please raise a specific proposal for how the resolving logic should work if you think this behaviour should be different.
