### ISSUE TITLE
Permission denied using charm push

### ISSUE THREAD

**Issue by jcsackett** [juju/charmstore#853]
On a jenkins job that publishes charms for release, we're seeing the following failure:

```
++ /snap/bin/charm push /var/lib/jenkins/workspace/livepatch-server-charm/charm-output/xenial/livepatch-health 'cs:~yellow/xenial/livepatch-health'
ERROR cannot post archive: cannot put archive blob: open 2a0100cf484eff84-bc98b165ca3fff56: permission denied
```

We've logged charm out on the machine and deleted go-cookies, and logged back in. The problem persists.

**Comment by mhilton** [comment]
This indicates that charmstore is having trouble authenticating with swift. I presume this is similar to #818.

**Comment by mhilton** [comment]
This was fixed by fixing the deployment scripts.
