### ISSUE TITLE
jujucharms.com redirect

### ISSUE THREAD

**Issue by xavpaice** [juju/charmstore#879]
URLs like https://jujucharms.com/rabbitmq-server or https://jujucharms.com/u/canonical-bootstack/infra-node/ are now returning 404 rather than redirecting to jaas.ai - can we add some kind of redirect for these?

**Comment by hatched** [comment]
@xavpaice I'm not able to reproduce that 404. Can you try in an incognito tab?

FYI for future reference these types of issues can be reported here: https://github.com/canonical-web-and-design/jaas.ai/issues

**Comment by xavpaice** [comment]
https://jujucharms.com/u/canonical-bootstack/infra-node/ returns a 404 in Firefox incognito, and also chromium.

**Comment by hatched** [comment]
That's interesting...it's working on all of my devices.

We have had one other who reported a similar issue and the resolution was to clear their local DNS cache. For whatever reason it was pointing to the old IP of jujucharms.com, are you able to give that a try?

**Comment by xavpaice** [comment]
Yes!  that was it - thanks for the help.

FTR: `sudo systemd-resolve --flush-caches`
