### ISSUE TITLE
Issue with charm write permissions for cs:~huntdatacenter/alerta

### ISSUE THREAD

**Issue by ghost** [juju/charmstore#895]
From IRC chat #juju with @mitechie.

We have a charm `cs:~huntdatacenter/alerta` under the namespace/team `huntdatacenter` that somehow ended up missing its write permissions for the `huntdatacenter` group.

Any chance you could help set the write permissions to `huntdatacenter` again?

**Comment by matuskosut** [comment]
After first fix for `cs:~huntdatacenter/alerta-2` we have permissions set to:
```
Read			huntdatacenter
Write			huntdatacenter
```

but those do not appear with earlier revisions:

```
charm show cs:~huntdatacenter/alerta
Alerta

Name			alerta
Owner			huntdatacenter
Revision			1
Supported Series	xenial, bionic
Tags			monitoring, alerta
Subordinate		false
Promulgated		false
Home page		https://github.com/huntdatacenter/alerta-charm/
Bugs url			https://github.com/huntdatacenter/alerta-charm/issues
Read			everyone
Write

CHANNEL		CURRENT
stable			true
``` 

I tried to push one more revision in case, which set permissions same way as for revision 2, but I cannot release either revision 2 or 3. Ending with `ERROR cannot release charm or bundle: access denied for user "matuskosut"`, even `charm whoami` reports user and group correctly so I expect missing permissions still to be an issue.

**Comment by howbazaar** [comment]
We think this has been addressed now, please let us know if there are still issues.
